### ISSUE TITLE
npm not found

### ISSUE THREAD

**Issue by RespectPick** [tarampampam/node-docker#7]
Firstly I tried to install via docker-compose

```
services:
  node:
    image: tarampampam/node:13.7-alpine
    volumes:
    - ./:/var/www/app
    working_dir: /var/www/app
    command: []
```

then I tried to run

`docker-compose run --rm node npm run dev`

and got 

`Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"npm\": executable file not found in $PATH": unknown`

If I try to connect via bash and do 

`npm run dev`

i got

`bash: npm: command not found`
